In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.random.randint(0,100,[61,50]))
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,63,98,82,48,50,33,65,80,70,81,...,45,18,16,38,0,17,4,33,58,62
1,47,54,16,38,47,29,34,45,22,9,...,2,18,98,37,89,65,85,45,96,36
2,4,65,57,54,74,89,64,1,95,73,...,2,20,10,52,99,42,5,64,14,22
3,91,12,42,95,65,10,30,45,93,47,...,80,73,71,38,7,83,63,35,5,67
4,63,45,13,24,80,13,85,56,41,14,...,60,25,49,91,31,12,61,93,83,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,46,55,31,73,3,7,17,21,61,81,...,82,58,49,82,66,21,8,40,94,94
57,28,66,77,36,96,89,34,93,59,53,...,46,30,36,8,24,13,61,0,54,11
58,54,48,47,66,60,88,69,64,40,39,...,74,69,22,29,76,91,14,38,82,86
59,71,44,3,52,51,83,21,84,45,65,...,82,28,51,1,2,29,80,39,62,43
60,86,12,66,67,3,88,33,27,9,0,...,57,39,96,85,55,29,71,90,23,48

In [43]:
pd.options.styler

In [31]:
pd.options.display.min_rows

10

In [34]:
pd.options.display.min_rows = 20

In [37]:
pd.options.display.max_rows = 90

In [38]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,90,62,85,62,34,8,3,94,69,67,...,37,65,82,2,89,24,11,26,72,81
1,44,63,92,5,64,95,32,43,90,76,...,13,92,65,53,74,72,30,39,89,67
2,61,28,95,33,41,93,97,8,49,7,...,75,72,82,7,96,45,1,88,1,30
3,11,35,75,11,48,84,25,62,77,1,...,25,46,33,89,48,56,49,69,42,98
4,51,90,60,52,10,7,26,57,93,44,...,73,95,86,90,31,77,80,54,26,63
5,83,1,57,48,83,65,55,63,32,93,...,92,7,11,76,57,78,48,62,78,83
6,40,30,22,47,99,98,64,40,21,5,...,81,55,33,4,30,85,90,4,91,39
7,38,4,27,55,39,67,61,25,10,18,...,86,84,92,2,21,14,76,91,70,80
8,46,14,19,36,34,0,7,37,11,92,...,63,10,85,54,40,37,65,69,90,67
9,20,4,54,19,32,90,29,30,27,13,...,22,46,75,94,60,78,32,93,96,70
10,55,79,94,30,2,71,45,59,98,7,...,44,15,88,61,79,94,4,78,41,14
11,46,47,50,68,80,74,9,24,5,62,...,97,32,31,93,8,53,3,34,21,87
12,9,20,45,44,23,31,39,10,56,8,...,89,72,55,9,63,24,83,99,6,45
13,40,78,11,47,15,81,48,14,34,55,...,72,27,3,63,54,42,96,89,65,50
14,35,94,22,72,69,37,75,43,4,48,...,34,94,22,56,24,88,11,85,5,98
15,53,47,86,16,87,78,80,73,45,17,...,60,19,11,98,90,62,10,12,61,77
16,42,84,39,30,18,71,84,42,47,40,...,34,65,58,10,79,93,6,97,85,77
17,66,15,39,58,73,6,45,95,8,83,...,49,5,86,15,42,3,37,4,7,67
18,9,19,60,35,28,16,72,22,40,9,...,32,2,89,17,20,79,33,76,64,87
19,76,6,29,24,74,2,1,40,45,49,...,57,43,72,53,91,73,45,40,41,80
20,59,0,78,80,48,8,27,25,36,8,...,49,1,10,87,91,27,17,10,32,89
21,66,48,41,6,20,99,24,76,32,24,...,0,81,11,58,27,11,66,73,3,31
22,38,23,65,57,96,69,37,90,43,25,...,35,46,86,33,19,98,63,20,96,30
23,93,5,21,77,95,30,90,26,51,94,...,62,72,41,75,51,90,85,85,23,18
24,96,93,17,6,75,6,8,39,64,55,...,62,16,9,26,47,67,14,69,77,16
25,54,84,95,54,18,91,79,6,29,83,...,75,55,14,57,92,69,56,10,85,55
26,43,14,34,26,70,11,46,89,98,68,...,19,68,48,54,65,77,48,85,45,18
27,40,64,18,50,46,92,7,47,97,34,...,66,17,39,22,27,31,85,63,24,18
28,39,51,5,54,50,83,14,54,1,50,...,98,22,65,49,80,85,95,39,28,26
29,77,63,55,67,53,75,19,20,84,6,...,90,94,82,45,20,98,40,63,4,72
30,64,64,1,45,85,84,47,93,92,23,...,95,85,19,35,4,2,88,74,7,70
31,68,8,12,76,50,2,64,31,72,68,...,60,5,98,50,13,29,58,82,34,31
32,16,59,94,37,27,98,66,5,20,98,...,87,6,79,38,42,18,81,23,41,9
33,97,18,7,72,88,24,60,93,9,2,...,1,84,7,42,55,21,59,73,87,67
34,1,58,88,82,20,98,63,85,30,97,...,81,9,77,55,42,79,51,8,25,61
35,15,45,89,7,77,96,73,23,34,23,...,75,41,81,33,58,66,82,39,90,70
36,87,9,95,91,73,86,45,79,71,55,...,83,63,37,47,23,95,48,48,70,28
37,3,11,45,86,28,30,8,68,23,60,...,27,2,57,87,92,58,23,72,35,98
38,42,9,2,73,95,9,68,87,83,46,...,53,48,74,27,85,59,83,51,85,50
39,85,25,86,22,26,56,60,35,27,34,...,35,84,36,14,23,93,91,5,63,86
40,65,35,7,45,89,79,18,6,43,18,...,89,81,97,51,90,35,47,26,5,59
41,65,41,71,60,20,23,29,33,15,46,...,35,22,62,85,44,35,69,97,66,19
42,97,15,1,81,42,37,32,43,3,86,...,7,35,37,25,32,91,24,31,13,41
43,13,53,49,93,32,77,47,32,85,2,...,92,28,24,80,46,16,71,61,22,24
44,22,59,25,41,71,94,87,14,11,38,...,64,31,34,56,13,6,74,78,68,71
45,20,13,58,73,54,87,11,64,24,36,...,6,81,94,38,64,95,34,0,99,81
46,54,26,97,93,10,57,23,20,37,35,...,48,90,45,5,65,39,75,41,68,84
47,2,67,36,69,54,51,19,8,85,12,...,57,79,79,49,60,80,92,97,83,26
48,83,53,99,65,38,66,10,38,62,64,...,59,31,41,36,54,61,6,31,32,62
49,35,41,43,68,43,74,84,47,91,55,...,63,93,12,84,15,53,7,9,78,15
50,43,15,67,68,32,87,67,54,94,83,...,78,58,54,47,53,76,34,12,73,99
51,75,93,96,25,68,23,31,69,1,80,...,1,42,92,52,21,67,57,45,17,76
52,70,62,86,73,52,33,30,63,85,39,...,79,79,72,23,86,93,35,20,55,28
53,67,53,18,68,42,23,52,97,82,24,...,55,44,76,24,33,2,24,22,16,81
54,40,25,37,60,6,7,36,59,85,78,...,9,14,31,19,3,64,79,84,92,68
55,75,62,34,92,99,76,78,16,98,54,...,98,88,54,86,51,43,31,61,79,50
56,70,17,90,49,9,64,21,55,0,13,...,43,73,79,41,27,5,6,98,8,86
57,14,59,8,7,91,10,38,45,14,57,...,32,7,22,71,38,58,55,22,25,28
58,44,77,76,70,80,26,4,69,17,56,...,43,51,87,72,46,31,68,69,56,47
59,34,8,35,53,44,12,30,5,29,36,...,60,76,89,94,19,24,36,61,61,42
60,5,48,27,34,35,93,45,0,41,71,...,55,69,53,75,84,93,69,48,30,69

In [39]:
pd.options.display.max_columns = 30

In [41]:
pd.options.display.max_columns = None

In [42]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,90,62,85,62,34,8,3,94,69,67,94,37,99,24,6,16,37,79,30,50,60,62,91,62,14,51,84,36,66,71,44,30,14,67,57,13,82,72,83,78,37,65,82,2,89,24,11,26,72,81
1,44,63,92,5,64,95,32,43,90,76,72,58,66,14,6,65,69,55,9,30,27,12,28,88,88,10,4,1,12,58,22,28,75,32,70,42,13,65,86,22,13,92,65,53,74,72,30,39,89,67
2,61,28,95,33,41,93,97,8,49,7,32,12,19,9,57,19,26,97,54,58,13,36,92,46,13,85,93,83,26,94,15,46,24,13,34,20,0,12,61,94,75,72,82,7,96,45,1,88,1,30
3,11,35,75,11,48,84,25,62,77,1,80,40,17,25,3,83,65,9,55,36,75,3,5,87,27,57,42,20,68,98,4,74,98,15,33,42,44,67,83,68,25,46,33,89,48,56,49,69,42,98
4,51,90,60,52,10,7,26,57,93,44,96,76,22,41,54,63,6,86,33,15,17,69,6,12,89,59,77,26,94,99,44,9,82,63,46,75,52,10,73,46,73,95,86,90,31,77,80,54,26,63
5,83,1,57,48,83,65,55,63,32,93,37,27,48,58,17,95,49,95,66,93,79,54,89,36,31,14,23,62,94,1,44,98,77,43,21,56,49,94,73,80,92,7,11,76,57,78,48,62,78,83
6,40,30,22,47,99,98,64,40,21,5,65,73,98,64,50,54,89,5,1,13,6,41,67,17,88,79,13,3,0,8,5,29,53,34,77,15,23,62,68,32,81,55,33,4,30,85,90,4,91,39
7,38,4,27,55,39,67,61,25,10,18,92,27,37,22,20,67,71,24,93,44,99,24,6,87,33,0,29,7,57,63,62,10,13,62,65,88,92,6,54,30,86,84,92,2,21,14,76,91,70,80
8,46,14,19,36,34,0,7,37,11,92,7,22,51,46,9,91,3,32,71,99,13,26,34,99,73,13,29,46,6,81,55,27,78,67,35,29,37,12,74,6,63,10,85,54,40,37,65,69,90,67
9,20,4,54,19,32,90,29,30,27,13,64,54,85,36,87,81,0,16,77,6,14,93,24,48,53,44,27,47,93,21,29,85,52,5,81,5,28,37,44,38,22,46,75,94,60,78,32,93,96,70
10,55,79,94,30,2,71,45,59,98,7,85,90,76,59,99,91,62,27,96,38,83,13,2,93,17,99,90,15,15,64,1,6,64,22,91,59,70,86,76,93,44,15,88,61,79,94,4,78,41,14
11,46,47,50,68,80,74,9,24,5,62,68,17,10,21,85,95,51,33,66,56,91,27,58,61,11,71,80,81,90,6,92,78,42,98,81,61,21,21,49,1,97,32,31,93,8,53,3,34,21,87
12,9,20,45,44,23,31,39,10,56,8,27,7,41,10,70,70,56,27,87,62,95,76,7,51,3,67,64,14,74,9,31,10,61,82,74,82,68,8,31,62,89,72,55,9,63,24,83,99,6,45
13,40,78,11,47,15,81,48,14,34,55,72,29,34,78,45,17,43,61,61,20,45,43,60,61,60,29,31,35,54,1,0,34,37,61,62,85,56,48,45,93,72,27,3,63,54,42,96,89,65,50
14,35,94,22,72,69,37,75,43,4,48,22,66,87,36,4,52,59,46,23,13,89,73,12,68,76,60,42,2,1,61,19,7,65,85,8,38,63,16,57,72,34,94,22,56,24,88,11,85,5,98
15,53,47,86,16,87,78,80,73,45,17,90,57,33,53,75,36,99,12,70,9,35,67,13,5,14,48,15,52,86,52,56,35,38,8,38,66,38,57,46,99,60,19,11,98,90,62,10,12,61,77
16,42,84,39,30,18,71,84,42,47,40,46,29,14,2,56,88,99,41,20,41,38,84,5,49,65,63,26,31,0,10,51,84,29,25,77,3,46,20,39,27,34,65,58,10,79,93,6,97,85,77
17,66,15,39,58,73,6,45,95,8,83,20,82,93,27,36,4,38,59,22,7,62,14,8,0,27,30,16,47,36,33,98,81,40,81,14,77,83,1,20,31,49,5,86,15,42,3,37,4,7,67
18,9,19,60,35,28,16,72,22,40,9,61,55,20,26,50,67,1,71,70,81,13,41,1,92,23,90,82,53,14,12,68,55,21,67,46,69,23,33,76,24,32,2,89,17,20,79,33,76,64,87
19,76,6,29,24,74,2,1,40,45,49,42,86,6,1,2,88,64,6,10,29,88,35,0,58,75,69,81,2,46,12,99,8,91,56,58,82,2,95,35,86,57,43,72,53,91,73,45,40,41,80
20,59,0,78,80,48,8,27,25,36,8,56,30,33,21,34,1,22,41,24,78,94,14,12,69,9,83,59,28,91,29,83,44,23,10,79,27,64,62,99,47,49,1,10,87,91,27,17,10,32,89
21,66,48,41,6,20,99,24,76,32,24,26,4,81,36,65,74,81,33,45,97,35,69,60,53,58,96,93,85,4,71,73,93,8,29,65,22,94,16,1,41,0,81,11,58,27,11,66,73,3,31
22,38,23,65,57,96,69,37,90,43,25,51,26,35,72,32,66,10,68,31,53,62,38,1,5,60,59,93,95,13,60,10,49,34,3,7,36,65,73,53,81,35,46,86,33,19,98,63,20,96,30
23,93,5,21,77,95,30,90,26,51,94,75,26,28,37,9,51,99,23,15,3,68,80,23,29,84,66,6,41,6,21,48,41,64,58,64,67,40,71,57,64,62,72,41,75,51,90,85,85,23,18
24,96,93,17,6,75,6,8,39,64,55,61,48,36,44,21,84,67,63,53,24,24,33,56,96,30,89,51,74,86,35,89,71,60,76,11,42,43,12,33,86,62,16,9,26,47,67,14,69,77,16
25,54,84,95,54,18,91,79,6,29,83,29,69,97,65,67,97,70,81,34,48,69,72,2,48,94,60,4,48,41,56,25,19,43,53,49,91,16,10,11,26,75,55,14,57,92,69,56,10,85,55
26,43,14,34,26,70,11,46,89,98,68,54,39,99,8,78,10,75,21,56,96,19,80,29,84,21,79,64,22,48,43,12,41,22,30,15,42,99,86,96,71,19,68,48,54,65,77,48,85,45,18
27,40,64,18,50,46,92,7,47,97,34,26,40,50,46,53,10,60,48,27,57,34,48,1,47,47,38,6,80,88,11,74,26,58,1,50,99,74,70,46,77,66,17,39,22,27,31,85,63,24,18
28,39,51,5,54,50,83,14,54,1,50,75,67,52,54,15,93,38,13,33,28,57,27,18,95,47,75,11,71,59,24,56,20,12,67,57,48,45,75,55,31,98,22,65,49,80,85,95,39,28,26
29,77,63,55,67,53,75,19,20,84,6,54,37,18,10,33,61,64,66,98,56,95,42,32,9,88,82,6,29,2,68,68,98,31,45,85,46,33,92,87,16,90,94,82,45,20,98,40,63,4,72
30,64,64,1,45,85,84,47,93,92,23,74,84,44,15,8,9,96,64,81,16,68,46,72,39,40,70,14,96,89,40,52,46,22,10,84,77,90,59,34,74,95,85,19,35,4,2,88,74,7,70
31,68,8,12,76,50,2,64,31,72,68,41,91,29,41,94,91,10,98,20,66,6,94,3,33,71,35,44,83,9,69,71,31,15,79,21,53,12,12,78,50,60,5,98,50,13,29,58,82,34,31
32,16,59,94,37,27,98,66,5,20,98,12,40,35,83,95,66,22,70,77,27,64,35,77,81,24,71,18,98,24,17,64,86,4,82,40,72,11,37,59,1,87,6,79,38,42,18,81,23,41,9
33,97,18,7,72,88,24,60,93,9,2,35,81,60,31,93,25,81,1,79,27,48,77,60,21,23,96,18,81,94,82,0,87,13,99,80,41,54,90,46,74,1,84,7,42,55,21,59,73,87,67
34,1,58,88,82,20,98,63,85,30,97,16,68,6,76,85,90,26,78,57,1,30,60,70,25,70,94,66,73,24,48,2,82,91,4,2,0,80,50,32,69,81,9,77,55,42,79,51,8,25,61
35,15,45,89,7,77,96,73,23,34,23,24,22,18,36,58,94,82,36,26,11,71,25,26,83,80,91,88,43,60,73,1,88,37,36,95,22,92,70,50,59,75,41,81,33,58,66,82,39,90,70
36,87,9,95,91,73,86,45,79,71,55,40,35,0,21,61,13,77,70,89,19,60,75,26,54,40,32,31,85,80,78,43,7,47,61,18,94,1,63,33,51,83,63,37,47,23,95,48,48,70,28
37,3,11,45,86,28,30,8,68,23,60,64,51,40,48,25,7,36,57,28,8,58,60,61,67,30,85,21,9,41,17,16,64,21,50,72,96,18,85,14,39,27,2,57,87,92,58,23,72,35,98
38,42,9,2,73,95,9,68,87,83,46,20,48,71,39,57,70,5,64,56,68,27,29,0,49,23,20,23,11,69,37,99,17,58,4,42,98,88,71,25,35,53,48,74,27,85,59,83,51,85,50
39,85,25,86,22,26,56,60,35,27,34,40,46,47,93,11,83,93,11,18,44,13,79,44,84,3,66,46,49,22,12,48,49,71,7,25,59,89,95,35,57,35,84,36,14,23,93,91,5,63,86
40,65,35,7,45,89,79,18,6,43,18,22,19,77,49,66,71,41,26,7,83,79,36,93,93,95,63,94,61,54,83,24,6,3,78,81,50,66,2,7,17,89,81,97,51,90,35,47,26,5,59
41,65,41,71,60,20,23,29,33,15,46,58,21,43,48,91,35,48,17,12,40,59,23,78,41,10,55,38,92,61,73,84,59,9,31,6,3,40,87,13,72,35,22,62,85,44,35,69,97,66,19
42,97,15,1,81,42,37,32,43,3,86,2,77,19,34,12,57,85,84,0,43,52,67,97,55,27,65,46,89,19,21,47,13,61,98,9,70,94,15,12,62,7,35,37,25,32,91,24,31,13,41
43,13,53,49,93,32,77,47,32,85,2,55,41,1,66,31,61,41,47,64,32,3,9,30,33,2,29,74,16,20,99,33,60,58,15,46,0,87,3,53,22,92,28,24,80,46,16,71,61,22,24
44,22,59,25,41,71,94,87,14,11,38,79,91,96,19,21,48,42,64,36,78,16,26,3,66,36,38,38,98,61,19,39,82,14,70,39,48,97,96,20,9,64,31,34,56,13,6,74,78,68,71
45,20,13,58,73,54,87,11,64,24,36,27,60,81,23,27,76,50,35,20,88,4,52,70,61,18,44,26,12,68,99,90,62,37,67,25,29,93,74,26,31,6,81,94,38,64,95,34,0,99,81
46,54,26,97,93,10,57,23,20,37,35,62,87,18,6,68,19,2,42,75,84,0,38,74,94,78,38,59,54,86,56,71,71,49,53,81,31,97,49,66,68,48,90,45,5,65,39,75,41,68,84
47,2,67,36,69,54,51,19,8,85,12,77,95,45,26,71,93,44,94,47,4,54,31,4,5,62,95,94,79,87,51,65,34,87,26,82,74,89,10,46,70,57,79,79,49,60,80,92,97,83,26
48,83,53,99,65,38,66,10,38,62,64,59,98,6,22,50,39,26,79,44,27,54,45,89,30,7,68,30,3,43,62,10,0,83,4,25,35,31,58,96,20,59,31,41,36,54,61,6,31,32,62
49,35,41,43,68,43,74,84,47,91,55,1,35,43,1,40,62,28,71,91,5,78,93,32,6,33,84,95,42,78,25,82,26,90,94,27,43,80,9,7,60,63,93,12,84,15,53,7,9,78,15
50,43,15,67,68,32,87,67,54,94,83,61,90,38,56,42,47,68,63,70,94,30,13,14,49,60,51,96,90,21,27,6,61,67,35,2,59,96,55,72,92,78,58,54,47,53,76,34,12,73,99
51,75,93,96,25,68,23,31,69,1,80,61,7,26,84,34,58,32,51,26,36,16,52,16,21,64,54,6,14,16,84,43,24,57,60,42,19,19,12,25,47,1,42,92,52,21,67,57,45,17,76
52,70,62,86,73,52,33,30,63,85,39,53,64,12,2,0,3,68,47,11,88,42,3,32,43,48,77,15,35,3,76,89,58,14,66,63,65,25,36,54,7,79,79,72,23,86,93,35,20,55,28
53,67,53,18,68,42,23,52,97,82,24,99,1,27,57,44,84,87,94,18,94,28,31,26,68,21,99,12,4,0,87,96,44,27,21,89,24,54,36,33,87,55,44,76,24,33,2,24,22,16,81
54,40,25,37,60,6,7,36,59,85,78,55,36,88,79,97,93,69,20,21,26,68,24,84,75,12,94,90,9,75,8,67,54,50,59,30,61,45,22,98,2,9,14,31,19,3,64,79,84,92,68
55,75,62,34,92,99,76,78,16,98,54,88,13,57,17,98,92,90,3,31,63,57,14,28,72,27,30,67,20,66,56,58,45,13,4,45,85,64,90,58,74,98,88,54,86,51,43,31,61,79,50
56,70,17,90,49,9,64,21,55,0,13,95,99,4,81,27,8,46,89,85,34,33,3,18,90,58,5,18,73,42,63,79,62,2,91,17,98,86,66,71,20,43,73,79,41,27,5,6,98,8,86
57,14,59,8,7,91,10,38,45,14,57,84,5,35,43,73,63,11,53,76,86,49,2,4,60,73,24,92,62,72,85,3,95,27,21,43,97,51,96,16,13,32,7,22,71,38,58,55,22,25,28
58,44,77,76,70,80,26,4,69,17,56,60,30,15,41,44,43,34,3,93,99,71,94,96,21,53,55,27,50,28,2,7,26,42,85,12,33,95,11,11,71,43,51,87,72,46,31,68,69,56,47
59,34,8,35,53,44,12,30,5,29,36,69,49,69,31,52,73,83,88,74,51,40,80,55,83,17,16,36,92,25,56,80,67,18,92,51,86,20,65,70,18,60,76,89,94,19,24,36,61,61,42
60,5,48,27,34,35,93,45,0,41,71,60,51,4,31,78,39,1,83,13,33,26,0,72,39,92,54,87,94,75,27,84,96,40,40,94,88,44,44,60,63,55,69,53,75,84,93,69,48,30,69

In [18]:
df

    0   1   2   3   4   5   6   7   ...  42  43  44  45  46  47  48  49
0   63  98  82  48  50  33  65  80  ...  16  38   0  17   4  33  58  62
1   47  54  16  38  47  29  34  45  ...  98  37  89  65  85  45  96  36
2    4  65  57  54  74  89  64   1  ...  10  52  99  42   5  64  14  22
3   91  12  42  95  65  10  30  45  ...  71  38   7  83  63  35   5  67
4   63  45  13  24  80  13  85  56  ...  49  91  31  12  61  93  83  83
..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..
56  46  55  31  73   3   7  17  21  ...  49  82  66  21   8  40  94  94
57  28  66  77  36  96  89  34  93  ...  36   8  24  13  61   0  54  11
58  54  48  47  66  60  88  69  64  ...  22  29  76  91  14  38  82  86
59  71  44   3  52  51  83  21  84  ...  51   1   2  29  80  39  62  43
60  86  12  66  67   3  88  33  27  ...  96  85  55  29  71  90  23  48

[61 rows x 50 columns]

In [21]:
pd.options.display.min_rows
pd.options.display.max_rows
pd.options.display.max_columns

16

In [22]:
# resetear la operacion
pd.get_option("display.min_rows")

10

In [25]:
pd.get_option("display.max_rows")

16

In [26]:
pd.get_option("display.max_columns")

16

In [29]:
# nuevo valor
pd.set_option("display.max_columns", 20)
pd.set_option("display.max_rows", 60)

In [31]:
pd.describe_option("display.max_rows")

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]

In [37]:
pd.describe_option("display.max_columns")

display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: 20]

In [36]:
pd.describe_option("display.min_rows")

display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]

In [35]:
pd.reset_option("display.min_rows")
pd.reset_option("display.max_rows")
pd.reset_option("display.max_columns")

In [ ]:
# ajuste de puntos decimales

In [50]:
df = pd.DataFrame(np.random.randn(5,5))
df

          0         1         2         3         4
0  0.617371 -0.438156  0.126695  0.676851 -2.262976
1  1.042229  0.951941 -0.262917 -2.766596  1.839249
2 -0.386495 -1.294046  1.606383  0.506323  0.943789
3  0.644617 -0.925542  0.338948 -0.736900 -1.805499
4  1.258894 -0.243909 -0.473031 -0.984898 -1.373708

In [51]:
pd.options.display.precision

6

In [52]:
pd.get_option("display.precision")

6

In [53]:
pd.set_option("display.precision", 6)
df

          0         1         2         3         4
0  0.617371 -0.438156  0.126695  0.676851 -2.262976
1  1.042229  0.951941 -0.262917 -2.766596  1.839249
2 -0.386495 -1.294046  1.606383  0.506323  0.943789
3  0.644617 -0.925542  0.338948 -0.736900 -1.805499
4  1.258894 -0.243909 -0.473031 -0.984898 -1.373708

In [55]:
df.iloc[0,3]

0.6768507337737703